version: '3.6'

services:
  cryptography:
    container_name: cryptography
    image: ${DOCKER_REGISTRY-}cryptography
    restart: unless-stopped
    build:
      context: .
      dockerfile: Docker.Cryptography/Dockerfile
      args:
        - TAG=8.0-alpine
    tty: true
    volumes:
      - ./.volumes/secrets:/app/secrets
    environment:
      - TZ=Europe/Amsterdam
      - AllowedHosts=localhost;*.local
